version: '3.2'

services:
  chat_server:
    build:
      context: ./app
    networks:
      - my_network
    ports:
      - "8528:8528"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - chat_db

  chat_db:
    image: postgres:11.2
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - my_network
    ports:
      - "25432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - chat_postgres_data:/var/lib/postgresql/data # 永続化

volumes:
  chat_postgres_data:

networks:
  my_network:
    driver: bridge