version: '3.2'

services:
  chat_server:
    build:
      context: ./app
    networks:
      - my_network
    ports:
      - "8528:8528"
    environment:
      # サーバー初期値
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8528
      # データベース初期値
      PSQL_HOST: chat_db
      PSQL_PORT: 5432
      PSQL_DATABASE: postgres
      PSQL_USER: postgres
      PSQL_PASSWORD: password
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - chat_db

  chat_db:
    image: postgres:11.2
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - my_network
    ports:
      - "25432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - chat_postgres_data:/var/lib/postgresql/data # 永続化

volumes:
  chat_postgres_data:

networks:
  my_network:
    driver: bridge